spring:
    application:
        name: 'invoices-back'
    datasource:
        url: jdbc:mysql://localhost:3306/invoices
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver